COMMON_FLAGS="-O2 -march=native -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# 24 threads for a 14700kf
MAKEOPTS="-j24 -l20"
PORTAGE_NICENESS=15

USE="wayland nvidia pipewire elogind dbus bluetooth opengl \
     alsa pulseaudio proprietary-codecs \
     -systemd -kde -gnome -aqua -cdrom -dvd"

# Language and Environment
LC_MESSAGES=C.UTF-8
L10N="en en-US"

# Hardware Specifics
VIDEO_CARDS="nvidia"
INPUT_DEVICES="libinput"
GRUB_PLATFORMS="efi-64"

PYTHON_TARGETS="python3_12"
PYTHON_SINGLE_TARGET="python3_12"

# Features
# 'ccache' speeds up recompiles, 'parallel-install' is faster
FEATURES="parallel-install parallel-fetch"

# Acceptance
# Allow proprietary drivers/firmware
ACCEPT_LICENSE="*"
FETCHCOMMAND="wget -t 3 -4 -O \"\${DISTDIR}/\${FILE}\" \"\${URI}\""
