
$HYPRSCRIPT=$HOME/.config/hypr/scripts

$terminal = kitty
$browser = librewolf-bin
$files = nautilus
$editor = zeditor
$zoom = woomer
$music = spotify
$menu = rofi
$bar = waybar

$colorPicker = hyprpicker -a -fhex
$takeScreenshot = hyprshot --mode=region --freeze --output-folder=Media/Screenshots
$nextKbdLayout = hyprctl switchxkblayout logitech-usb-receiver-keyboard next
$startTimer = $HYPRSCRIPT/timer
$pickEmoji = $menu -show emoji
$toggleDebugOverlay = $HYPRSCRIPT/toggle_debug_overlay
$activateMenu = killall $menu || $menu -show combi
$toggleBar = killall -SIGUSR1 $bar

exec-once = $bar
# exec-once = flatpak override --user --filesystem=/run/user/1000/pipewire-0 com.dec05eba.gpu_screen_recorder && flatpak run com.dec05eba.gpu_screen_recorder gsr-ui
exec-once = blueman-applet
exec-once = gsr-ui
exec-once = hyprpm reload
exec-once = waycorner
exec-once = udiskie
exec-once = dunst
exec-once = hypridle
exec-once = nm-applet
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
#exec-once = pipewire &
#exec-once = wireplumber &
exec-once = gentoo-pipewire-launcher restart
exec-once = pavucontrol
exec-once = sudo mount --mkdir /dev/sda2 /run/media/lain/temp
exec-once = swww-daemon
exec-once = swww img /home/lain/Pictures/bg_dark_anim_0_08.gif
exec-once = /usr/libexec/hyprpolkitagent
# exec-once = hyprsunset

